apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot
spec:
  selector:
    matchLabels:
      app: iot
  template:
    metadata:
      labels:
        app: iot
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: iot
        image: w0n9/iot_bridge_golang:v0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9580
          name: http
        volumeMounts:
        - name: iot-config
          mountPath: /usr/src/app/config.yaml
          subPath: config.yaml
      volumes:
        - name: iot-config
          configMap:
            name: iot-config